### ISSUE TITLE
Google sheets denining permishon

### ISSUE THREAD

**Issue by CoderThomasB** [CoderThomasB/AoTawhiti-Tv#1]
the url https://spreadsheets.google.com/feeds/cells/1MOTvNV6NNkCuLdYN3JU2ctiFhELxWg1EW_qusrWEGHo/1/public/logout
responds with a error saying that You need permission to access this published document.

**Comment by CoderThomasB** [comment]
This is a problem with the permissions on the sheets. I will try and ask the owner to change it.

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by CoderThomasB** [comment]
This issue has been fixed with the move to the new google sheets API.
